### ISSUE TITLE
"pip install ninfo" not runable

### ISSUE THREAD

**Issue by shane-kerr** [JustinAzoff/ninfo#20]
I tried the simplest install using `pip`:
```
$ mkdir ninfo
$ cd ninfo
$ python3 -m venv venv
$ source venv/bin/activate
$ python3 -m pip install --upgrade pip
$ python3 -m pip install ninfo
```

Then I tried to list modules:
```
$ ninfo -l
Traceback (most recent call last):
  File "/home/shane/tmp/ninfo/venv/bin/ninfo", line 5, in <module>
    from ninfo import main
  File "/home/shane/tmp/ninfo/venv/lib/python3.12/site-packages/ninfo/__init__.py", line 1, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```

This is on an otherwise working Ubuntu system:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
$ uname -a
Linux earth 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ python3 -V
Python 3.12.3
```

**Comment by JustinAzoff** [comment]
ah, this is due to python3.12 deprecating installing those modules by default and that API:

https://github.com/mu-editor/mu/issues/2485

In the meantime, `python3 -m pip install setuptools` will get things working and that can be added as a dependency.
